### ISSUE TITLE
Website AWA.FM

### ISSUE THREAD

**Issue by nenarindra** [franklai/lyric-get-js#18]
There is a new source of Japanese song lyrics called AWA.FM, mainly for accomodating artists with digital releases.
[Main Site](https://awa.fm/)
[Lyrics Example](https://s.awa.fm/track/935f96064c61504c2539)

Please kindly update for your Lyrics Get site so that I can extract the lyrics. Thank you.

![Screen Shot 2024-11-03 at 00 49 13](https://github.com/user-attachments/assets/42a3aec6-139d-42b6-881b-15fda4f41fe4)

**Comment by franklai** [comment]
fixed in https://github.com/franklai/lyric-get-js/commit/f503a27ad3a516913190d16e360957d17ebc2886

deployed to
- https://franks543-lyric-get.vercel.app/
- https://franks543-lyric-get.netlify.app/

**Comment by nenarindra** [comment]
Much appreciated. Arigatou gozaimasu.
